# Generated by Django 4.0.5 on 2022-06-05 17:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Repository',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.CharField(max_length=200)),
                ('repository', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='repositories', to='main_app.githubaccount')),
            ],
            options={
                'ordering': ['url'],
            },
        ),
        migrations.CreateModel(
            name='Language',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('repository', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='languages', to='main_app.repository')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Branch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('repository', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='branches', to='main_app.repository')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
    ]
