# Generated by Django 4.0.5 on 2022-06-05 17:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_repository_language_branch'),
    ]

    operations = [
        migrations.RenameField(
            model_name='repository',
            old_name='repository',
            new_name='githubaccount',
        ),
    ]
