# Generated by Django 4.0.5 on 2022-06-06 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0005_vulnerability'),
    ]

    operations = [
        migrations.AlterField(
            model_name='language',
            name='name',
            field=models.CharField(default='None', max_length=100),
        ),
    ]
