# Generated by Django 4.0.5 on 2022-06-06 14:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0007_remove_language_repository'),
    ]

    operations = [
        migrations.AddField(
            model_name='language',
            name='repository',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='languages', to='main_app.repository'),
        ),
    ]
